<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>


    <!-- Permalinks -->
    <div class="postbox tweakr-postbox">
    <h3 class="hndle"><span><?php _e('Permalinks', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

        <h4>Insert-Dialogs</h4>

        <p>Virtual Permlinks can be used by the Editor Insert-Dialogs to avoid issues with static links (Link + Media Dialog).</p>

        <?php 
            // Virtual Permalinks
            $this->_settingsUtility->displayCheckbox(__('Virtual Permalinks', 'tweakr'), 'permalinks-virtual', array(
                'label' => 'Enable Virtual Permalink URLs',
                'description' => 'Placeholders like link://post.local/1234 are used within the Insert-Dialogs and got replaced by the real link during rendering - this avoids problems with different domains names.'
            ));
        ?>

        <h4>Permalink Structure</h4>

        <p>The WordPress Core rewrite rules will be altered to add the .html extension to the following elements</p>

        <?php 
             // Add .html to Pages
            $this->_settingsUtility->displayCheckbox(__('Pages', 'tweakr'), 'rewrites-page-ext-html', array(
                'label' => 'Add .html extension to all pages.'
            ));

            // Add .html to Categories
            $this->_settingsUtility->displayCheckbox(__('Categories', 'tweakr'), 'rewrites-category-ext-html', array(
                'label' => 'Add .html extension to all categories.'
            ));

            // Add .html to custom Taxonomies
            $this->_settingsUtility->displayCheckbox(__('Taxonomies', 'tweakr'), 'rewrites-custom-taxonomy-ext-html', array(
                'label' => 'Add .html extension to custom taxonomies.'
            ));

            // Remove Trailing-Slashes
            $this->_settingsUtility->displayCheckbox(__('Trailing Slashes', 'tweakr'), 'rewrites-trailingslashes-remove', array(
                'label' => 'Remove trailing slashes from all permalinks'
            ));
        ?>


    <!-- // Permalinks -->
    </div></div>

    <!-- XML Sitemap -->
    <div class="postbox tweakr-postbox">
    <h3 class="hndle"><span><?php _e('Sitemap', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

        <p>Provides a XML Sitemap for Search Engines regarding the <a href="https://www.sitemaps.org/" target="_new">sitemaps.org</a> specification. Includes all published posts and pages.</p>

        <?php 
            // Add virtual sitemap.xml
            $this->_settingsUtility->displayCheckbox(__('XML Sitemap', 'tweakr'), 'sitemap-xml-enabled', array(
                'label' => 'Enable',
                'description' => 'Automatically generated /sitemap.xml file.',
                'readmore' => 'https://www.sitemaps.org/protocol.html'
            ));

            // Advertise sitemap.xml in robots.txt
            $this->_settingsUtility->displayCheckbox(__('Advertise XML Sitemap', 'tweakr'), 'sitemap-xml-robotstxt', array(
                'label' => 'Add link to robots.txt',
                'description' => 'Advertise sitemap.xml address in robots.txt file. This allows search engines to recognize the sitemap automatically.',
                'readmore' => 'https://www.sitemaps.org/protocol.html'
            ));
        ?>

        <?php 
             
        ?>

    <!-- // XML Sitemap -->
    </div></div>
