<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<hr />
<p class="credits">
    <a href="https://andidittrich.de/go/tweakr">Tweakr</a> <?php _e('is developed by', 'tweakr'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> and <a href="https://aenon-dynamics.com">Aenon Dynamics</a>.
    <?php printf(__('It`s released under the terms of the %s', 'tweakr'), '<a href="#TB_inline?width=800&height=550&inlineId=tweakr-license" class="thickbox">'.__('GPL-2.0', 'cryptex').'</a>'); ?>
    <br /><strong><?php _e('Includes:', 'tweakr'); ?></strong>
    <a href="https://github.com/AndiDittrich/WP-Skeleton">WP-Skeleton</a> <?php _e('by', 'tweakr'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> - MPL-2.0 <?php _e('License', 'tweakr'); ?>;
</p>
<hr />