<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>


    <!-- TinyMCE -->
    <div class="postbox">
    <h3 class="hndle"><span><?php _e('Visual Editor (TinyMCE)', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

        <h4><?php _e('General Settings', 'tweakr'); ?></h4>

        <?php 
            // Enable
            $this->_settingsUtility->displayCheckbox(__('Autowidth', 'tweakr'), 'tinymce-autowidth', array(
                'label' => 'Enable automatic width',
                'description' => 'Removes the fixed-width restriction and set it to auto (80 percent of maximal available width will be used).'
            ));

        ?>

    <!-- // TinyMCE -->
    </div></div>
