<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>


    <!-- Permalink -->
    <div class="postbox">
    <h3 class="hndle"><span><?php _e('Permalink Strcuture', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

        <h4><?php _e('Enhancements', 'tweakr'); ?></h4>

        <?php 

        ?>

    <!-- // Permalink -->
    </div></div>

    <!-- Rewrite Rules -->
    <div class="postbox">
    <h3 class="hndle"><span><?php _e('Rewrite Rules', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

    <!-- // Rewrite Rules -->
    </div></div>
