<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="postbox">
<h3 class="hndle"><?php _e('Tweakr Related', 'tweakr'); ?></h3>
<div class="inside">
<!-- Metabox-Content -->
    <p><?php _e('Got a problem ? Need support or want to request a new feature ?', 'tweakr'); ?></p>
    <ul>
        <li><a href="http://wordpress.org/support/plugin/tweakr"><?php _e('Support Forum', 'tweakr'); ?></a></li>
        <li><a href="https://github.com/AndiDittrich/WordPress.Tweakr"><?php _e('Tweakr on GitHub', 'tweakr'); ?></a></li>
        <li><a href="https://wordpress.org/plugins/tweakr/faq/"><?php _e('FAQ', 'tweakr'); ?></a></li>
        <li><a href="http://wordpress.org/plugins/tweakr/"><?php _e('Tweakr on WordPress.org', 'tweakr'); ?></a></li>
        <li><a href="https://github.com/AndiDittrich/WordPress.Tweakr/issues"><?php _e('Report a Bug', 'tweakr'); ?></a></li>
        <li><a href="https://andidittrich.de/"><?php _e('Author`s Website', 'tweakr'); ?></a></li>
    </ul>
<!-- // Metabox-Content -->
</div></div>