<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>
<?php add_thickbox(); ?>

<!-- TweakrSettings:wrap -->
<div class="wrap" id="tweakr-settings">

<!-- Settings Tabs -->
<h2 class="nav-tab-wrapper" id="tweakr-tabnav">
    <a data-tab="TweakrTabTweaks" class="nav-tab"><?php _e('Tweaks', 'tweakr'); ?></a>
    <a data-tab="TweakrTabContent" class="nav-tab"><?php _e('Content', 'tweakr'); ?></a>
    <a data-tab="TweakrTabEditing" class="nav-tab"><?php _e('Editing', 'tweakr'); ?></a>
    <a data-tab="TweakrTabAnalytics" class="nav-tab"><?php _e('Analytics', 'tweakr'); ?></a>
    <a data-tab="TweakrTabPrivacy" class="nav-tab"><?php _e('Privacy', 'tweakr'); ?></a>
    <a data-tab="TweakrTabSystem" class="nav-tab"><?php _e('System', 'tweakr'); ?></a>
</h2>

<!-- Main Title -->
<h1 class="maintitle"><span class="tweakr-title-badge"></span><?php echo TWEAKR_PLUGIN_TITLE; ?></h1>
<p><?php echo TWEAKR_PLUGIN_HEADLINE; ?></p>

<!-- settings !-->
<form method="post" action="options.php">
    <?php settings_fields('tweakr-settings-group' ); ?>
    <!-- #poststuff -->
    <div id="poststuff">

<!-- 2 Column Layout -->
<div id="post-body" class="metabox-holder columns-2">
    <div id="post-body-content">
             
        <div id="TweakrTabTweaks">
        <?php require (TWEAKR_PLUGIN_PATH . '/views/admin/Tweaks.phtml'); ?>
        </div>

        <div id="TweakrTabContent">
        <?php require (TWEAKR_PLUGIN_PATH . '/views/admin/Content.phtml'); ?>
        </div>

        <div id="TweakrTabEditing">
        <?php require (TWEAKR_PLUGIN_PATH . '/views/admin/Editing.phtml'); ?>
        </div>

        <div id="TweakrTabAnalytics">
        <?php require (TWEAKR_PLUGIN_PATH . '/views/admin/Analytics.phtml'); ?>
        </div>

        <div id="TweakrTabPrivacy">
        <?php require (TWEAKR_PLUGIN_PATH . '/views/admin/Privacy.phtml'); ?>
        </div>

        <div id="TweakrTabSystem">
        <?php require (TWEAKR_PLUGIN_PATH . '/views/admin/System.phtml'); ?>
        </div>
        
        <!-- submit !-->
        <?php submit_button(); ?>

    </div>
    <!-- // MAIN COLUMN -->
    
    <!-- Right Column -->
    <div id="postbox-container-1" class="postbox-container">
        <?php require(TWEAKR_PLUGIN_PATH . '/views/admin/SystemInfo.phtml'); ?>
        
        <?php require(TWEAKR_PLUGIN_PATH . '/views/admin/Related.phtml'); ?>
    </div>
    <!-- // Right Column -->
    
</div>
<!-- // 2 Column Layout -->

</div>
<!-- // #poststuff -->

</form>
<div class="clear"></div>
<hr />
<p class="credits">
    <a href="https://andidittrich.de/go/tweakr">Tweakr</a> <?php _e('is developed by', 'tweakr'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> and <a href="https://aenon-dynamics.com">Aenon Dynamics</a>.
    <?php printf(__('It`s released under the terms of the %s', 'tweakr'), '<a href="#TB_inline?width=800&height=550&inlineId=tweakr-license" class="thickbox">'.__('GPL-2.0', 'cryptex').'</a>'); ?>
    <br /><strong><?php _e('Includes:', 'tweakr'); ?></strong>
    <a href="https://github.com/AndiDittrich/WP-Skeleton">WP-Skeleton</a> <?php _e('by', 'tweakr'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> - MPL-2.0 <?php _e('License', 'tweakr'); ?>;
</p>

<?php require(TWEAKR_PLUGIN_PATH . '/views/admin/License.phtml'); ?>

</div>
<!-- // TweakrSettings:wrap -->

<div class="clear"></div>