<?php
/**
    Descriptionn: TWEAKR Admin Settings Page
    Plugin URI: https://andidittrich.de/go/tweakr
    Version: 1.0
    Author: Andi Dittrich
    Author URI: https://andidittrich.de
    License: MIT X11-License
    
    Copyright (c) 2016-2017, Andi Dittrich

    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>
<?php add_thickbox(); ?>

<!-- TweakrSettings:wrap -->
<div class="wrap" id="tweakr-settings">

<!-- Settings Tabs -->
<h2 class="nav-tab-wrapper" id="tweakr-tabnav">
    <a data-tab="TweakrTabTweaks" class="nav-tab"><?php _e('Tweaks', 'tweakr'); ?></a>
    <a data-tab="TweakrTabEditing" class="nav-tab"><?php _e('Editing', 'tweakr'); ?></a>
    <a data-tab="TweakrTabAnalytics" class="nav-tab"><?php _e('Analytics', 'tweakr'); ?></a>
    <a data-tab="TweakrTabSystem" class="nav-tab"><?php _e('System', 'tweakr'); ?></a>
</h2>

<!-- Main Title -->
<h1 class="maintitle"><span class="tweakr-title-badge"></span><?php _e('Tweakr Toolkit', 'tweakr'); ?></h1>
<p>Supercharges your Blog with common used Tweaks, Features and Utilities</p>

<!-- settings !-->
<form method="post" action="options.php">
    <?php settings_fields('tweakr-settings-group' ); ?>
    <!-- #poststuff -->
    <div id="poststuff">

<!-- 2 Column Layout -->
<div id="post-body" class="metabox-holder columns-2">
    <div id="post-body-content">
             
        <div id="TweakrTabTweaks">
        <?php require ('Tweaks.phtml'); ?>
        </div>

        <div id="TweakrTabEditing">
        <?php require ('Editing.phtml'); ?>
        </div>

        <div id="TweakrTabAnalytics">
        <?php require ('Analytics.phtml'); ?>
        </div>

        <div id="TweakrTabSystem">
        <?php require ('System.phtml'); ?>
        </div>
        
        <!-- submit !-->
        <?php submit_button(); ?>

    </div>
    <!-- // MAIN COLUMN -->
    
    <!-- Right Column -->
    <div id="postbox-container-1" class="postbox-container">
        <?php require('SystemInfo.phtml'); ?>
        
        <?php require('Related.phtml'); ?>
    </div>
    <!-- // Right Column -->
    
</div>
<!-- // 2 Column Layout -->

</div>
<!-- // #poststuff -->

</form>
<div class="clear"></div>
<hr />
<p class="credits">
    <a href="https://andidittrich.de/go/tweakr">Tweakr</a> <?php _e('is developed by', 'tweakr'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> and <a href="https://aenon-dynamics.com">Aenon Dynamics</a>.
    <?php printf(__('It`s released under the terms of the %s', 'tweakr'), '<a href="#TB_inline?width=800&height=550&inlineId=tweakr-license" class="thickbox">'.__('MIT X11 License', 'tweakr').'</a>'); ?>
    <br /><strong><?php _e('Includes:', 'tweakr'); ?></strong>
    <a href="https://github.com/js-cookie/js-cookie/">js-cookie</a> <?php _e('by', 'tweakr'); ?> <a href="https://twitter.com/carhartl">Klaus Hartl</a> - MIT <?php _e('License', 'tweakr'); ?>;
    | <a href="https://github.com/AndiDittrich/WP-Skeleton">WP-Skeleton</a> <?php _e('by', 'tweakr'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> - MIT <?php _e('License', 'tweakr'); ?>;
</p>

<?php require('License.phtml'); ?>

</div>
<!-- // TweakrSettings:wrap -->

<div class="clear"></div>