<?php if (!defined('TWEAKR_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

    <!-- Frontend -->
    <div class="postbox">
    <h3 class="hndle"><span><?php _e('Frontend', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

        <?php

            // Hide Generator Tag
            $this->_settingsUtility->displayCheckbox(__('Generator Tag', 'tweakr'), 'hide-generator', array(
                'label' => 'Hide WordPress Generator Tag',
                'description' => 'The Generator Meta Tag displays your current WordPress Version.'
            ));

            // Hide Adminbar
            $this->_settingsUtility->displayCheckbox(__('Adminbar', 'tweakr'), 'hide-adminbar', array(
                'label' => 'Global hide Admin-Toolbar',
                'description' => 'Maybe you do not need the Admin Toolbar or it breaks your theme styles.'
            ));

            // hide Windows Live Writer manifest file link
            $this->_settingsUtility->displayCheckbox(__('Windows Live Writer Manifest', 'tweakr'), 'hide-wlwmlink', array(
                'label' => 'Hide Windows Live Writer Manifest Link',
                'description' => 'Windows Live Writer is an application for managing blog post. If you do not need it, disable the link.'
            ));

            // Hide Meta Pagination
            $this->_settingsUtility->displayCheckbox(__('Meta Pagination', 'tweakr'), 'hide-meta-pagination-link', array(
                'label' => 'Hide Meta Pagination Links',
                'description' => 'These Links contains the next/prev page used for page preloading.'
            ));

            // Disable Emojis
            $this->_settingsUtility->displayCheckbox(__('Emojis', 'tweakr'), 'disable-emojis', array(
                'label' => 'Disable Emojis',
                'description' => 'In case you do not like the Emoji icons - this option also disables related scripts/styles.',
                'readmore' => 'https://codex.wordpress.org/Emoji'
            ));

            // Disable OEmbeds
            $this->_settingsUtility->displayCheckbox(__('oEmbed', 'tweakr'), 'disable-oembed', array(
                'label' => 'Disable oEmbeds',
                'description' => 'Removes related tags, scripts, permalinks and endpoints.'
            ));

             // Hide Resource Hints
            $this->_settingsUtility->displayCheckbox(__('Resource Hints', 'tweakr'), 'hide-resource-hints', array(
                'label' => 'Hide Resource Hints',
                'description' => 'Standard Resource Hints might not be useful (like w.org). This option will hide all registered types.'
            ));

        ?>

    <!-- // Frontend -->
    </div></div>

    <!-- Feeds -->
    <div class="postbox">
    <h3 class="hndle"><span><?php _e('Feeds (RSS/RDF/ATOM)', 'tweakr'); ?></span></h3>
    <div class="inside tweakr-setting-section">

        <?php

            // Disable Feed Links
            $this->_settingsUtility->displayCheckbox(__('Links', 'tweakr'), 'hide-feed-link', array(
                'label' => 'Hide Feed Links',
                'description' => 'Removes the Content and Comments Feed links from your Site.',
                'readmore' => 'https://codex.wordpress.org/WordPress_Feeds'
            ));

            // Disable RSS
            $this->_settingsUtility->displayCheckbox(__('RSS', 'tweakr'), 'disable-rss', array(
                'label' => 'Disable RSS Feeds',
                'description' => 'Removes RSS Endpoints from Content and Comments. User get redirected to homepage.',
                'readmore' => 'https://codex.wordpress.org/WordPress_Feeds'
            ));

            // Disable Atom
            $this->_settingsUtility->displayCheckbox(__('Atom', 'tweakr'), 'disable-atom', array(
                'label' => 'Disable Atom Feeds',
                'description' => 'Removes Atom Endpoints from Content and Comments. User get redirected to homepage.',
                'readmore' => 'https://codex.wordpress.org/WordPress_Feeds'
            ));

            // Disable RDF
            $this->_settingsUtility->displayCheckbox(__('RDF', 'tweakr'), 'disable-rdf', array(
                'label' => 'Disable RDF Feeds',
                'description' => 'Removes the RDF Endpoint. User get redirected to homepage.',
                'readmore' => 'https://codex.wordpress.org/WordPress_Feeds'
            ));

            // Disable Feed Rewrites
            $this->_settingsUtility->displayCheckbox(__('Rewrite Rules', 'tweakr'), 'rewrites-disable-feeds', array(
                'label' => 'Disable Feed Rewrite Rules',
                'description' => 'In case you have already disabled all feeds it is also possible to remove the related rewrite rules.'
            ));
        ?>

    <!-- // Feeds -->
    </div></div>

    