<p>Just insert a email-address surrounded by cryptex shortcode into your post! - That`s it!<br />
Cryptex provides two shortcodes for interoperable usage. Both are doing exactly the same!</p>

<p><strong>Standard (E-Mail): </strong>
<code>[email]my.address@example.com[/email]</code></p>

<p><strong>Standard (Telephone Numbers): </strong>
<code>[telephone]+49 30 1234 5678[/telephone]</code></p>

<p>To avoid namespace collisions with other plugins, you can disable the <code>[email]</code> and <code>[telephone]</code> shortcode alias (advanced settings).<br />
In this case you can still use the cryptex plugin with the following legacy shortcode (already used by plugin version 1+2):</p>

<p><strong>Legacy Shortcode: </strong>
<code>[cryptex]my.address@example.com[/cryptex]</code></p>